import type { DeckId, PromptDefinition } from '@decoy/types';

type OpinionSeed = [category: string, text: string];
type TriviaSeed = [category: string, text: string, canonicalAnswer: string];

function buildOpinionPrompt(deckId: DeckId, index: number, [category, text]: OpinionSeed): PromptDefinition {
  return {
    id: `${deckId}-${index + 1}`,
    deckId,
    archetype: 'opinion_vote',
    resolutionType: 'audience_vote',
    category,
    text,
    votePrompt: 'Vote for the funniest, boldest, or most believable answer. No self-votes.'
  };
}

function buildTriviaPrompt(deckId: DeckId, index: number, [category, text, canonicalAnswer]: TriviaSeed): PromptDefinition {
  return {
    id: `${deckId}-${index + 1}`,
    deckId,
    archetype: 'bluff_trivia',
    resolutionType: 'correct_answer',
    category,
    text,
    canonicalAnswer,
    votePrompt: 'Which answer is the real one? Pick carefully.'
  };
}

const truthComesOutSeeds: OpinionSeed[] = [
  ['Social survival', 'What is something you have pretended to enjoy just to fit in?'],
  ['Group chat crimes', 'What is the pettiest reason you have ever muted a group chat?'],
  ['Secret habits', 'What is your most embarrassing comfort-food combination?'],
  ['Career chaos', 'What is the weirdest thing you have ever done to look busy at work?'],
  ['Low-stakes lies', 'What is a harmless lie you tell about yourself way too often?'],
  ['Personal branding', 'What is the least accurate compliment people keep giving you?'],
  ['Travel', 'What is the most dramatic overreaction you have had on a trip?'],
  ['Fashion regrets', 'What trend did you defend long after it was clearly over?'],
  ['Family lore', 'What is the strangest rule your family treated as normal?'],
  ['School memories', 'What is the most ridiculous excuse you used for missing homework?'],
  ['Friendship', 'What is one habit your friends probably roast you for in private?'],
  ['Tiny betrayals', 'What is a tiny betrayal that hurts you way more than it should?'],
  ['Food diplomacy', 'What dish do you praise in public but avoid in private?'],
  ['Dating', 'What is the smallest red flag that immediately ruins your interest in someone?'],
  ['Money habits', 'What is the dumbest thing you have rationalized buying?'],
  ['Nostalgia', 'What childhood obsession would be impossible to defend now?'],
  ['Party stories', 'What is the quickest way you have ever killed the vibe in a room?'],
  ['Home life', 'What is the messiest part of your home that guests are never allowed to see?'],
  ['Digital life', 'What app would expose the most embarrassing version of you?'],
  ['Petty victories', 'What is the smallest argument you still think you absolutely won?'],
  ['Self awareness', 'What is a personality flaw you insist is actually a feature?'],
  ['Public behavior', 'What is something you judge people for while secretly doing yourself?'],
  ['First impressions', 'What is the weirdest thing you want people to know about you immediately?'],
  ['Sibling energy', 'What is the most sibling-coded thing you have ever done to a friend?'],
  ['Weekend energy', 'What is your most unrealistic weekend ambition?'],
  ['Workplace theater', 'What is your favorite fake-professional phrase to hide confusion?'],
  ['Taste crimes', 'What is your worst take that you still defend with confidence?'],
  ['Phone habits', 'What is the most cursed photo still living in your camera roll?'],
  ['Public transport', 'What is the most feral thing you have seen and pretended not to see in public?'],
  ['Romantic delusion', 'What is the most delusional sign you have mistaken for flirting?'],
  ['Kitchen failures', 'What meal do you cook with completely unjustified confidence?'],
  ['Secrets', 'What is something you would only confess if everyone else went first?'],
  ['Office politics', 'What is the most obvious thing you have ever blamed on "the system"?'],
  ['Music taste', 'What song do you know is terrible but would still play at full volume?'],
  ['Shopping', 'What is the weirdest impulse buy you somehow still defend?'],
  ['Gym behavior', 'What is the biggest lie people tell at the gym?'],
  ['Pet peeves', 'What tiny behavior turns you into a full-time hater?'],
  ['Vacation mode', 'What is your most unrealistic vacation personality?'],
  ['Household politics', 'What is the smallest domestic hill you are willing to die on?'],
  ['Dating apps', 'What profile detail makes you swipe away instantly?'],
  ['Social media', 'What is the most embarrassing thing you have posted and left up anyway?'],
  ['Bragging rights', 'What is the most useless thing you are strangely proud of?'],
  ['Excuses', 'What is the flimsiest excuse that somehow worked for you?'],
  ['Food opinions', 'What food opinion makes people look at you like a villain?'],
  ['Fashion crimes', 'What item in your closet keeps surviving every clean-out for no good reason?'],
  ['Texts from hell', 'What text message do you wish you could permanently unsend from history?'],
  ['Team sports', 'What role do you secretly believe you would dominate in despite zero evidence?'],
  ['Commuting', 'What is your most irrational commuting superstition?'],
  ['Sleep habits', 'What bedtime behavior would make you sound like a menace?'],
  ['Pride and shame', 'What skill do you brag about even though nobody asked?'],
  ['Host energy', 'What is the least subtle way you hint that people should leave your house?'],
  ['Online shopping', 'What product review have you written in your head but never posted?'],
  ['Bad decisions', 'What is the quickest route from "This seems fine" to total chaos for you?'],
  ['Daily nonsense', 'What tiny inconvenience can ruin your entire mood for hours?'],
  ['Core memory', 'What is the most accidental flex you have ever pulled off?']
];

const nakedTruthSeeds: OpinionSeed[] = [
  ['Dating stories', 'What is the most embarrassing date story you can tell without naming names?'],
  ['Flirting fails', 'What is the least smooth thing you have ever said while trying to flirt?'],
  ['Late-night chaos', 'What is the most questionable text you have sent after midnight?'],
  ['Bedroom diplomacy', 'What is the weirdest thing you have done to seem cooler than you were?'],
  ['Crush behavior', 'What is your most unhinged harmless crush behavior?'],
  ['Adulting', 'What is the most grown-up setting where you have still acted like a teen?'],
  ['Ex energy', 'What is the pettiest thought an ex still inspires in you?'],
  ['Romantic delusion', 'What is the biggest red flag you excused because someone was hot?'],
  ['Party aftermath', 'What is the worst morning-after realization you have ever had?'],
  ['Secrets', 'What is something you absolutely should have kept between you and your diary?'],
  ['Hookup logistics', 'What is the least sexy practical problem that has ruined the mood for you?'],
  ['Compliments', 'What compliment would work on you immediately even if it should not?'],
  ['Taste crimes', 'What thirst-trap behavior are you secretly susceptible to?'],
  ['Petty jealousy', 'What completely innocent thing can make you jealous anyway?'],
  ['Texts from hell', 'What is the riskiest typo you have ever sent to the wrong person?'],
  ['Confessions', 'What is the softest reason you have ever ghosted someone?'],
  ['Chaos', 'What is your most chaotic "this sounded better in my head" decision?'],
  ['Romance', 'What is the worst place to realize you are wildly overdressed for flirting?'],
  ['Boundaries', 'What is the fastest way for someone to fumble a good first impression with you?'],
  ['Bad ideas', 'What is one seductive bad idea you fall for every single time?'],
  ['Overconfidence', 'What are you weirdly overconfident about in romance despite the evidence?'],
  ['Self sabotage', 'What is the most effective way you accidentally sabotage your own vibe?'],
  ['Mild scandal', 'What is the smallest thing you do that feels illegal but absolutely is not?'],
  ['Tiny turn-offs', 'What ridiculously minor thing instantly kills your attraction?'],
  ['Cringe recovery', 'What is the least convincing line you have used to recover from embarrassment?'],
  ['Party lies', 'What lie have you told at a party because the truth felt somehow worse?'],
  ['Thirst mechanics', 'What is the most unserious thing that can make you blush anyway?'],
  ["Adult sleepovers", "What is the least glamorous thing about staying over at someone else's place?"],
  ['Messages', 'What emoji becomes suspicious in the wrong context way too fast?'],
  ['Situationships', 'What is the clearest sign someone is wasting your time?'],
  ['Fashion emergencies', 'What is the most inconvenient outfit decision you have made for attention?'],
  ['Public behavior', 'What public display of affection makes you instantly want to evaporate?'],
  ['Dating apps', 'What profile sentence guarantees chaos if you ignore it?'],
  ['Romantic optimism', 'What is the worst thing to hear right after you have emotionally committed?'],
  ['Mixed signals', 'What behavior do people call mysterious when it is actually just annoying?'],
  ['Text etiquette', 'What is the most revealing amount of time to wait before replying?'],
  ['Bar stories', 'What is the least sexy sentence you have heard in a bar?'],
  ['Temptation', 'What is one absolutely unserious trait that can still win you over?'],
  ["Regret management", "What is the first clue that tonight's decision will become next week's story?"],
  ['Hangover sociology', 'What is the funniest thing people pretend not to remember the next day?'],
  ['Cursed chemistry', 'What is the biggest warning sign that the chemistry is only in your imagination?'],
  ['Soft launches', 'What is the pettiest reason to refuse posting someone online?'],
  ['Flirty nonsense', 'What is something people think is bold and seductive but actually just confusing?'],
  ['Crowd behavior', 'What is the most suspicious place to run into an ex unexpectedly?'],
  ['Reputation', 'What rumor about your dating life would sound believable even if false?'],
  ['Bad timing', 'What is the funniest possible time for your confidence to disappear completely?'],
  ['Adult chaos', 'What is the least dignified reason to cancel a hot date?'],
  ['Jealousy theater', 'What is the most transparent attempt to make someone jealous?'],
  ['Party recovery', 'What snack is the universal symbol of bad decisions catching up with you?'],
  ['Flirting economy', 'What is the worst possible opener that still makes you laugh?'],
  ['Cuffing season', 'What is the real reason people become suddenly sentimental when it gets cold?'],
  ['Oversharing', 'What topic becomes too intimate way faster than people realize?'],
  ['Rebounds', 'What is the clearest sign someone is auditioning you for a bad idea?'],
  ['Tempting nonsense', 'What kind of terrible plan becomes persuasive after two compliments?'],
  ['Scandal control', 'What is the funniest possible phrase to hear before things go wildly off-script?']
];

const relationshipPartySeeds: OpinionSeed[] = [
  ['Friend group politics', 'What is one habit your friends secretly find annoying but politely endure?'],
  ['Couple energy', 'What is the biggest sign two people are trying too hard to seem unbothered?'],
  ['Pet peeves', 'What tiny habit in a shared space can start a ridiculous fight?'],
  ['Hosting', 'What is the loudest silent message a host can send that says "please leave"?'],
  ['Group dinners', 'What is the most suspicious thing someone can do when the bill arrives?'],
  ['Vacation mode', 'What role in a group trip causes the most chaos every single time?'],
  ['Friendship tests', 'What is the pettiest way to tell if someone is actually your real friend?'],
  ['House rules', 'What living-together argument is somehow never truly resolved?'],
  ['Party manners', 'What kind of guest instantly gets put on the mental never-again list?'],
  ['Advice', 'What terrible relationship advice keeps surviving because it sounds dramatic?'],
  ['Sibling-coded', 'What behavior makes two friends look like a married couple in denial?'],
  ['Texting', 'What response time starts a needless spiral in the group chat?'],
  ["Shared chores", "What household task reveals someone's actual character the fastest?"],
  ["Birthdays", "What is the least helpful role in planning a friend's birthday?"],
  ['Boundaries', 'What friendly phrase actually means "absolutely not"?'],
  ['Road trips', 'What is the earliest sign a road trip is about to go downhill?'],
  ['Roommate life', 'What is the most passive-aggressive way to ask for help cleaning up?'],
  ['Dinner parties', 'What food contribution screams "I forgot until ten minutes ago"?'],
  ['Jealousy', 'What totally ordinary thing sparks ridiculous friend-group jealousy?'],
  ['Introductions', 'What is the weirdest way a friend can sabotage your first impression?'],
  ['Photos', 'What role in a group photo always takes the task way too seriously?'],
  ['Couples games', 'What answer in a couples game should make everyone nervous immediately?'],
  ['Party survival', 'What is the best excuse to escape a conversation without being rude?'],
  ['Wedding chaos', 'What wedding role is just one stress fracture away from a meltdown?'],
  ['Friendship honesty', 'What is the kindest possible way to tell a friend they are being absurd?'],
  ['Double dates', 'What is the fastest way for a double date to become a hostage situation?'],
  ['Plans', 'What phrase guarantees the plan will never actually happen?'],
  ['Relationship mythology', 'What "cute couple thing" is secretly annoying in real life?'],
  ['Brunch', 'What brunch behavior should be classified as hostile?'],
  ['Trips', 'What is the most dangerous sentence to hear right before leaving on vacation with friends?'],
  ['Shared playlists', 'What song choice immediately exposes the wrong energy for the night?'],
  ["Group loyalty", "What is the pettiest reason to take a friend's side no matter what?"],
  ['Roommate diplomacy', 'What object in a shared home causes the dumbest territorial conflict?'],
  ['Couple habits', 'What small routine makes a couple look alarmingly codependent?'],
  ['Party etiquette', 'What is the clearest sign someone plans to overstay by several hours?'],
  ['Subtweets', 'What is the most transparent way to complain about a friend without naming them?'],
  ['Traveling pairs', 'What pair of personalities should never split one hotel room?'],
  ['Advice culture', 'What type of relationship advice is just gossip wearing a blazer?'],
  ['Group gift drama', 'What role in a group gift always ends in unpaid Venmo requests?'],
  ['Compromise', 'What is the fakest phrase people use when they are absolutely not compromising?'],
  ['Board games', 'What board-game behavior suggests deeper unresolved issues?'],
  ['Phone habits', 'What is the least subtle way to tell a friend their partner is the problem?'],
  ['Party cleanup', 'What cleanup strategy only the worst guest would call "helping"?'],
  ['Dinner seating', 'What seating arrangement instantly creates gossip?'],
  ['Friendship anniversaries', 'What counts as a deeply unserious but still meaningful friendship milestone?'],
  ['Couple arguments', 'What tiny disagreement has absolutely no business becoming a relationship saga?'],
  ['Secret signals', 'What look across a room means "we are leaving in ten minutes"?'],
  ['Group dynamics', 'What role in every friend group never asked for leadership but somehow has it anyway?'],
  ['Theme parties', 'What costume choice makes everyone assume drama is imminent?'],
  ['Boundaries', 'What favor sounds reasonable until you realize it will ruin your week?'],
  ['Housewarming', 'What gift announces you do not really know this person at all?'],
  ['Reputation', 'What harmless couple quirk becomes suspicious if they do it too confidently?'],
  ['Memories', 'What shared story gets funnier every year and less flattering every retelling?'],
  ['Friendship maintenance', 'What is the true sign someone is your real friend in a crisis?'],
  ['Brutal honesty', 'What truth can only be spoken inside a moving car or at brunch?']
];

const isThatAFactSeeds: TriviaSeed[] = [
  ['Food history', 'Bubble wrap was originally invented as what household product?', 'Wallpaper'],
  ['Nature', 'Sea otters hold hands while sleeping mainly so they do not do what?', 'Drift apart'],
  ['Animals', 'A group of flamingos is commonly called a what?', 'Flamboyance'],
  ['Sports history', 'The first basketball games were played using what as hoops?', 'Peach baskets'],
  ['Weather', 'The smell of rain on dry ground is commonly called what?', 'Petrichor'],
  ['Ancient history', 'The ancient Romans sometimes used crushed what in toothpaste?', 'Oyster shells'],
  ['Science', 'Bananas are slightly radioactive because they contain a lot of what element?', 'Potassium'],
  ['Maritime oddities', 'Lobsters were once so common in parts of North America that they were compared to what?', 'Insects'],
  ['Architecture', 'The tiny decorative metal cap on top of a spire is called a what?', 'Finial'],
  ["Inventions", "Velcro was inspired by burrs sticking to what?", "A dog's fur"],
  ['Space', 'The footprints on the Moon could last for millions of years because the Moon has almost no what?', 'Weather'],
  ['Language', 'The dot over a lowercase i or j has its own name. What is it?', 'Tittle'],
  ['Botany', 'Pineapples grow on what kind of plant structure?', 'A low flowering plant'],
  ['Music', 'A piano has 88 keys in its modern standard form, but how many pedals does most piano music assume?', 'Three'],
  ['Fashion history', 'The word denim comes from the French phrase for cloth from where?', 'Nimes'],
  ['Geography', 'Istanbul is the only major city that sits on how many continents?', 'Two'],
  ['Transport', 'The first speeding ticket for a car was reportedly issued at about what speed?', '8 mph'],
  ['Odd records', 'The unicorn is the national animal of which country?', 'Scotland'],
  ['Food science', 'Honey never spoils mainly because it has very little what?', 'Water'],
  ['Biology', 'Octopuses have how many hearts?', 'Three'],
  ['Human body', 'Your smallest bones are located in what part of the body?', 'The ear'],
  ['History', 'Napoleon was once attacked by a horde of what animals?', 'Rabbits'],
  ['Art materials', 'Traditional yellow school-bus paint was chosen partly because it contains undertones of what color?', 'Orange'],
  ['Ocean life', 'Starfish move using hundreds of tiny what?', 'Tube feet'],
  ["Flags", "Nepal's national flag is unusual because it is not what shape?", "Rectangular"],
  ['Food origins', 'Ketchup was once sold in the 1830s as a remedy for what?', 'Indigestion'],
  ['Birds', 'Crows can recognize and remember individual what?', 'Human faces'],
  ['Math history', 'The word algorithm comes from the Latinized name of what scholar?', 'Al-Khwarizmi'],
  ['Gardens', 'Carrots were first widely cultivated in what color before orange varieties became popular?', 'Purple'],
  ['Royal trivia', 'The Tower of London is famous for keeping which birds as symbolic residents?', 'Ravens'],
  ['Writing', 'The sentence "The quick brown fox jumps over the lazy dog" is an example of what?', 'A pangram'],
  ['Everyday objects', 'A shoelace tip is properly called an what?', 'Aglet'],
  ['Fossils', 'Paleontologists believe T. rex probably had feathers during at least part of whose life cycle?', 'Its ancestors or juveniles'],
  ['Engineering', 'The inventor of the frisbee was later famously turned into what after he died?', 'A memorial frisbee'],
  ['Astronomy', 'Venus spins in the opposite direction of most planets. This is called what kind of rotation?', 'Retrograde'],
  ['Food myths', 'White chocolate is missing the cocoa what found in dark chocolate?', 'Solids'],
  ["Parks", "The national park with the world's oldest known trees is in which U.S. state?", "California"],
  ['Animal senses', 'Sharks do not sleep like humans, but many must keep moving to push water over what?', 'Their gills'],
  ['Etymology', 'The word salary is often linked to the Latin word for what valuable seasoning?', 'Salt'],
  ['Plants', 'Sunflowers can remove certain toxic metals from soil in a process called what?', 'Phytoremediation'],
  ['Festivals', 'Confetti was originally made from what sugary treat in Italy?', 'Candied almonds'],
  ['Sound', 'The fear of long words is humorously named what?', 'Hippopotomonstrosesquipedaliophobia'],
  ['Technology', 'The first computer mouse was made partly out of what material?', 'Wood'],
  ["Maps", "The imaginary line used for the world's time zones runs nearest to which oceanic feature?", "The 180th meridian"],
  ['Toys', 'Rubber ducks squeak because of what trapped inside them?', 'Air'],
  ["Medicine history", "The stethoscope was invented because a doctor felt awkward placing his ear directly on what?", "A patient's chest"],
  ['Sports', 'Golf balls have dimples because the texture helps them do what?', 'Fly farther'],
  ['Food customs', 'Fortune cookies are more closely associated with which country than China in their modern form?', 'The United States'],
  ['Odd animals', 'Wombats produce what unusually shaped droppings?', 'Cube-shaped droppings'],
  ['Classic nonsense', 'The word "quarantine" originally referred to a period of how many days?', 'Forty']
];

const movieBluffSeeds: TriviaSeed[] = [
  ['Science fiction', 'What is the real plot of The Midnight Sky?', 'A lonely Arctic scientist tries to warn a returning space crew not to come back to a devastated Earth.'],
  ['Fantasy', 'What is the real plot of Stardust?', 'A young man enters a magical kingdom to retrieve a fallen star and discovers the star is a woman pursued by witches and princes.'],
  ['Comedy', 'What is the real plot of Best in Show?', 'Mockumentary chaos unfolds as eccentric dog owners compete at an elite dog show.'],
  ['Drama', 'What is the real plot of Little Miss Sunshine?', 'A dysfunctional family drives cross-country in a yellow van so their daughter can compete in a beauty pageant.'],
  ['Thriller', 'What is the real plot of The Game?', 'A wealthy banker becomes trapped in a terrifying immersive experience that blurs reality and manipulation.'],
  ['Adventure', 'What is the real plot of Romancing the Stone?', 'A romance novelist gets pulled into a treasure hunt in Colombia with a reckless adventurer.'],
  ['Mystery', 'What is the real plot of Knives Out?', 'A detective investigates the suspicious death of a rich novelist inside his spectacularly dysfunctional family.'],
  ["Animated", "What is the real plot of The Emperor's New Groove?", "A selfish emperor is turned into a llama and must rely on a peasant he previously mistreated."],
  ['Horror comedy', 'What is the real plot of Tucker and Dale vs. Evil?', 'Two kindhearted hillbillies are mistaken for killers by a group of panicked college students.'],
  ['Musical', 'What is the real plot of Sing Street?', 'A teen in 1980s Dublin starts a band to impress a girl and escape his collapsing home life.'],
  ['Noir', 'What is the real plot of Brick?', 'A high-school loner investigates a murder through a world styled like a hard-boiled noir.'],
  ['Crime comedy', 'What is the real plot of Logan Lucky?', 'Two brothers attempt to rob a NASCAR speedway during one of its busiest races.'],
  ['Fantasy adventure', 'What is the real plot of Time Bandits?', 'A boy joins a gang of time-traveling dwarves who steal treasure while fleeing an angry Supreme Being.'],
  ['Comedy drama', 'What is the real plot of Stranger Than Fiction?', 'An IRS auditor discovers his life is being narrated by a novelist who plans to kill him off.'],
  ['Sci-fi comedy', 'What is the real plot of Galaxy Quest?', 'Washed-up actors from a canceled sci-fi show are mistaken for real heroes by aliens.'],
  ['Adventure comedy', 'What is the real plot of O Brother, Where Art Thou?', 'Three escaped convicts wander Depression-era Mississippi in a loose retelling of The Odyssey.'],
  ['Romance', 'What is the real plot of The Lake House?', 'Two people living in the same house communicate across time through its mailbox.'],
  ['Dark comedy', 'What is the real plot of Death Becomes Her?', 'Two rivals drink a potion for eternal youth and discover immortality is deeply inconvenient.'],
  ["Action thriller", "What is the real plot of Run Lola Run?", "A woman races through Berlin in multiple timelines trying to save her boyfriend's life."],
  ['Family fantasy', 'What is the real plot of Jumanji?', 'A magical board game unleashes jungle danger into the real world until the players finish it.'],
  ['Supernatural comedy', 'What is the real plot of Beetlejuice?', 'A dead couple hires an obnoxious ghost to scare away the living family in their house.'],
  ['Drama', 'What is the real plot of Lars and the Real Girl?', 'A lonely man introduces his family to a life-size doll he treats as his girlfriend.'],
  ['Sci-fi mystery', 'What is the real plot of Coherence?', 'A dinner party unravels when a comet passes overhead and fractures reality into multiple versions.'],
  ['Fantasy', 'What is the real plot of The Fall?', 'A hospitalized stuntman tells an epic fantasy story to a young girl while manipulating her sympathy.'],
  ['Adventure', 'What is the real plot of Hunt for the Wilderpeople?', 'A rebellious foster kid and his grumpy guardian become the subjects of a nationwide manhunt in the New Zealand bush.'],
  ['Comedy', 'What is the real plot of Drop Dead Gorgeous?', 'Small-town beauty pageant contestants face increasingly absurd and deadly mishaps.'],
  ['Thriller', 'What is the real plot of Source Code?', 'A soldier relives the same train explosion repeatedly to identify the bomber.'],
  ['Fantasy comedy', 'What is the real plot of Penelope?', 'A woman cursed with a pig snout hides from society until she chooses her own life.'],
  ['Science fiction', 'What is the real plot of Moon?', 'A solitary lunar worker nears the end of his contract and discovers a disturbing truth about his identity.'],
  ['Adventure', 'What is the real plot of The Secret Life of Walter Mitty?', 'A daydreaming photo editor travels the world while searching for a missing negative.'],
  ['Mystery thriller', 'What is the real plot of Shutter Island?', 'A U.S. marshal investigates a disappearance at an island asylum while his own reality begins to crumble.'],
  ['Comedy', 'What is the real plot of Clue?', 'Dinner guests in a creepy mansion try to survive and solve a murder with multiple possible endings.'],
  ['Fantasy romance', 'What is the real plot of The Princess Bride?', 'A swashbuckling farm boy returns to rescue the woman he loves from an unwanted royal marriage.'],
  ["Dark fantasy", "What is the real plot of Pan's Labyrinth?", "A young girl in fascist Spain escapes into a magical labyrinth with dangerous tasks and eerie creatures."],
  ['Sci-fi action', 'What is the real plot of Edge of Tomorrow?', 'A soldier relives the same alien invasion day until he learns how to win it.'],
  ['Drama', 'What is the real plot of Chef?', 'A chef quits his restaurant job and reconnects with his son by launching a food truck.'],
  ['Heist', 'What is the real plot of Inside Man?', 'A detective negotiates a clever bank hostage crisis that hides a deeper motive.'],
  ['Fantasy comedy', 'What is the real plot of Enchanted?', 'A fairy-tale princess is pushed into real-life New York and has to survive modern cynicism.'],
  ['Sci-fi satire', 'What is the real plot of Sorry to Bother You?', 'A telemarketer discovers professional success by using a fake white voice and gets pulled into corporate nightmare fuel.'],
  ['Mystery', 'What is the real plot of The Nice Guys?', 'A bumbling enforcer and a private detective team up to solve a missing-person case in 1970s Los Angeles.'],
  ['Adventure comedy', 'What is the real plot of National Treasure?', 'A historian hunts for a hidden treasure by stealing the Declaration of Independence.'],
  ['Family fantasy', 'What is the real plot of Matilda?', 'A brilliant girl with neglectful parents discovers telekinetic powers and takes on a monstrous headmistress.'],
  ['Crime drama', 'What is the real plot of Fargo?', 'A desperate salesman hires criminals to kidnap his wife and triggers a spectacularly bad chain reaction.'],
  ["Supernatural fantasy", "What is the real plot of Big Fish?", "A son pieces together his dying father's larger-than-life stories to understand the man behind the myths."],
  ['Action comedy', 'What is the real plot of True Lies?', 'A secret agent hides his job from his family while chasing terrorists and rescuing his marriage.'],
  ['Animated fantasy', 'What is the real plot of Spirited Away?', 'A girl trapped in a spirit bathhouse works to free her parents after they are turned into pigs.'],
  ['Sci-fi noir', 'What is the real plot of Dark City?', 'A man with missing memories uncovers a city manipulated nightly by alien beings.'],
  ['Comedy mystery', 'What is the real plot of Murder by Death?', 'An eccentric millionaire invites famous detectives to his mansion for a murder-game prank that becomes real.'],
  ['Fantasy adventure', 'What is the real plot of The Adventures of Baron Munchausen?', 'The fabulist Baron recounts impossible adventures while trying to save a city under siege.'],
  ['Drama', 'What is the real plot of The Station Agent?', 'A quiet train enthusiast inherits a depot and slowly builds unlikely friendships.'],
  ['Monster movie', 'What is the real plot of Tremors?', 'Residents of a desert town fight giant underground worm monsters that sense vibrations.']
];

const wordUpSeeds: TriviaSeed[] = [
  ['Obscure words', 'What does the word "callipygian" mean?', 'Having notably shapely buttocks'],
  ['Obscure words', 'What does the word "petrichor" mean?', 'The earthy smell after rain'],
  ['Obscure words', 'What does the word "susurrus" mean?', 'A whispering or rustling sound'],
  ['Obscure words', 'What does the word "limerence" mean?', 'An intense state of romantic infatuation'],
  ['Obscure words', 'What does the word "defenestration" mean?', 'The act of throwing something or someone out of a window'],
  ['Obscure words', 'What does the word "agastopia" mean?', 'Admiration of a particular body part'],
  ['Obscure words', 'What does the word "clinomania" mean?', 'An excessive desire to stay in bed'],
  ['Obscure words', 'What does the word "absquatulate" mean?', 'To leave abruptly'],
  ['Obscure words', 'What does the word "ultracrepidarian" mean?', 'Someone who gives opinions beyond their knowledge'],
  ['Obscure words', 'What does the word "apercu" mean?', 'A concise insightful observation'],
  ['Obscure words', 'What does the word "zeugma" mean?', 'A figure of speech where one word governs two others in different senses'],
  ['Obscure words', 'What does the word "mellifluous" mean?', 'Sweetly smooth or musical sounding'],
  ['Obscure words', 'What does the word "syzygy" mean?', 'A straight-line alignment of celestial bodies'],
  ['Obscure words', 'What does the word "widdershins" mean?', 'In a direction opposite the usual or clockwise way'],
  ['Obscure words', 'What does the word "borborygmus" mean?', 'A rumbling sound in the stomach'],
  ['Obscure words', 'What does the word "floccinaucinihilipilification" mean?', 'The act of judging something as worthless'],
  ['Obscure words', 'What does the word "pogonotrophy" mean?', 'The cultivation of a beard'],
  ['Obscure words', 'What does the word "epistolary" mean?', 'Relating to letters or letter writing'],
  ['Obscure words', 'What does the word "crepuscular" mean?', 'Active at twilight'],
  ['Obscure words', 'What does the word "psithurism" mean?', 'The sound of wind in leaves'],
  ["Obscure words", "What does the word \"omphaloskepsis\" mean?", "Contemplation of one's own navel"],
  ['Obscure words', 'What does the word "nictitate" mean?', 'To blink'],
  ['Obscure words', 'What does the word "apricity" mean?', 'The warmth of the sun in winter'],
  ['Obscure words', 'What does the word "mondegreen" mean?', 'A misheard lyric or phrase'],
  ['Obscure words', 'What does the word "antediluvian" mean?', 'Ridiculously old-fashioned or from before the Biblical flood'],
  ['Obscure words', 'What does the word "pauciloquent" mean?', 'Using few words'],
  ['Obscure words', 'What does the word "xanthic" mean?', 'Yellowish in color'],
  ['Obscure words', 'What does the word "obambulate" mean?', 'To wander about'],
  ['Obscure words', 'What does the word "kakistocracy" mean?', 'Government by the least suitable people'],
  ['Obscure words', 'What does the word "hyggelig" mean?', 'Cozy, comfortable, and convivial'],
  ['Obscure words', 'What does the word "otiose" mean?', 'Serving no useful purpose; idle'],
  ["Obscure words", "What does the word \"chatoyant\" mean?", "Having a changeable luster like a cat's eye"],
  ['Obscure words', 'What does the word "respair" mean?', 'Fresh hope after a period of despair'],
  ['Obscure words', 'What does the word "farrago" mean?', 'A confused mixture'],
  ['Obscure words', 'What does the word "cacography" mean?', 'Bad handwriting or bad spelling'],
  ['Obscure words', 'What does the word "velleity" mean?', 'A wish too slight to lead to action'],
  ['Obscure words', 'What does the word "numinous" mean?', 'Having a mysterious spiritual quality'],
  ['Obscure words', 'What does the word "petrified" originally mean in geology?', 'Turned into stone'],
  ['Obscure words', 'What does the word "somnambulist" mean?', 'A sleepwalker'],
  ['Obscure words', 'What does the word "rhadamanthine" mean?', 'Strictly just or severe in judgment'],
  ['Obscure words', 'What does the word "ineffable" mean?', 'Too great or extreme to be expressed in words'],
  ['Obscure words', 'What does the word "anfractuous" mean?', 'Winding and full of bends'],
  ['Obscure words', 'What does the word "myrmidon" mean?', 'A loyal follower who executes orders without question'],
  ['Obscure words', 'What does the word "jentacular" mean?', 'Relating to breakfast'],
  ['Obscure words', 'What does the word "eldritch" mean?', 'Weird, eerie, or sinister'],
  ['Obscure words', 'What does the word "sobremesa" mean?', 'Time spent talking around the table after a meal'],
  ['Obscure words', 'What does the word "quomodocunquize" mean?', 'To make money by any means possible'],
  ['Obscure words', 'What does the word "corybantic" mean?', 'Wildly enthusiastic and frenzied'],
  ['Obscure words', 'What does the word "lugubrious" mean?', 'Exaggeratedly mournful or gloomy'],
  ['Obscure words', 'What does the word "tintinnabulation" mean?', 'A ringing or tinkling sound'],
  ['Obscure words', 'What does the word "peristeronic" mean?', 'Pertaining to pigeons']
];

const popCultureSeeds: TriviaSeed[] = [
  ['Before fame', 'Which future movie star once wore a giant chicken suit outside a fast-food restaurant?', 'Brad Pitt'],
  ['Before fame', 'Which Oscar winner once worked as a mortuary cosmetologist?', 'Whoopi Goldberg'],
  ['Before fame', 'Which actor trained lions as a teenager before becoming famous?', 'Christopher Walken'],
  ['Before fame', 'Which rock singer worked as a cemetery groundskeeper before his music career took off?', 'Jon Bon Jovi'],
  ['Before fame', 'Which actor worked as a wedding singer and party performer before becoming a movie star?', 'Adam Sandler'],
  ['Celebrity trivia', 'Which pop star was named after the heroine in a Dolly Parton song?', 'Miley Cyrus'],
  ['Celebrity trivia', 'Which actor legally changed his name from Nicolas Kim Coppola to avoid nepotism claims?', 'Nicolas Cage'],
  ["Celebrity trivia", "Which singer's full name is Stefani Joanne Angelina Germanotta?", "Lady Gaga"],
  ["Celebrity trivia", "Which rapper's real first name is Calvin?", "Snoop Dogg"],
  ['TV trivia', 'Which sitcom apartment building is known as 90 Bedford Street in New York City?', 'The one used for Friends'],
  ['Movie trivia', 'Which actor improvised the chest-thumping scene in The Wolf of Wall Street?', 'Matthew McConaughey'],
  ['Movie trivia', 'Which actress starred opposite Patrick Swayze in the pottery scene from Ghost?', 'Demi Moore'],
  ["Music trivia", "Which singer's stage name came from a Queen song?", "Lady Gaga"],
  ['Music trivia', 'Which singer starred on The Mickey Mouse Club alongside Britney Spears and Ryan Gosling?', 'Christina Aguilera'],
  ['Animation', 'What is the real first name of cartoon icon Hello Kitty according to Sanrio?', 'Kitty'],
  ["TV history", "Which late-night host used to write for Roseanne before hosting his own show?", "Conan O'Brien"],
  ['Film history', 'Which sci-fi franchise first used the phrase "May the Force be with you"?', 'Star Wars'],
  ['Celebrity pets', 'Which singer owns a famous cat named Olivia Benson?', 'Taylor Swift'],
  ['Award shows', 'Which actor accidentally announced the wrong Best Picture winner at the Oscars alongside Faye Dunaway?', 'Warren Beatty'],
  ['Streaming culture', 'Which show popularized the phrase "winter is coming"?', 'Game of Thrones'],
  ['Music videos', 'Which artist danced with zombies in the video for Thriller?', 'Michael Jackson'],
  ['Celebrity origins', 'What does the name "Keanu" in Keanu Reeves most commonly translate to?', 'Cool breeze over the mountains'],
  ['Comedy', 'Which comedian created both Parks and Recreation and The Good Place?', 'Michael Schur'],
  ['Hollywood lore', 'Which actress became a princess after marrying Prince Rainier III?', 'Grace Kelly'],
  ['Pop royalty', 'Which singer was nicknamed the Material Girl?', 'Madonna'],
  ['Reality TV', 'Which family built a media empire after Keeping Up with the Kardashians?', 'The Kardashians'],
  ['Blockbuster history', 'Which film was the first to earn over a billion dollars at the global box office?', 'Titanic'],
  ['Cult films', 'Which movie gave us the phrase "As if!"?', 'Clueless'],
  ["Animation", "Which Pixar film features emotions living inside a girl's mind?", "Inside Out"],
  ["Celebrity facts", "Which actor played Danny Ocean and has been named People's Sexiest Man Alive twice?", "George Clooney"],
  ['Stage names', 'Which singer was born Abel Tesfaye?', 'The Weeknd'],
  ['Stage names', 'Which singer was born Robyn Fenty?', 'Rihanna'],
  ['Stage names', 'Which rapper was born Aubrey Graham?', 'Drake'],
  ['TV catchphrases', 'Which reality franchise begins many seasons with someone declaring they are "not here to make friends"?', 'The Bachelor'],
  ["Music history", "Which band was originally called Kara's Flowers?", "Maroon 5"],
  ['Music history', 'Which singer had an alter ego named Sasha Fierce?', 'Beyonce'],
  ['Movie props', 'Which adventure franchise features a whip and a fedora as its most iconic costume pieces?', 'Indiana Jones'],
  ['Streaming hits', 'Which series centers on a Wednesday Addams attending Nevermore Academy?', 'Wednesday'],
  ['Fashion and fame', 'Which singer was once known for the meat dress at the 2010 MTV Video Music Awards?', 'Lady Gaga'],
  ['Celebrity businesses', 'Which actress founded Goop?', 'Gwyneth Paltrow'],
  ['Fandom', 'Which fantasy author created Westeros?', 'George R. R. Martin'],
  ["TV classics", "Which sitcom theme song promised \"I'll be there for you\"?", "Friends"],
  ['Movie casting', 'Which actor played both Jack Dawson and Jordan Belfort?', 'Leonardo DiCaprio'],
  ['Voice acting', 'Which actor voiced both Darth Vader and Mufasa?', 'James Earl Jones'],
  ['Broadway', 'Which musical begins with the song "Alexander Hamilton"?', 'Hamilton'],
  ['Comedy films', 'Which actor played Ron Burgundy?', 'Will Ferrell'],
  ['Teen movies', 'Which film warned us that on Wednesdays we wear pink?', 'Mean Girls'],
  ["Music tours", "Which singer's 2023-2024 stadium phenomenon was called The Eras Tour?", "Taylor Swift"],
  ['Celebrity aliases', 'Which actor is nicknamed The Rock?', 'Dwayne Johnson'],
  ['Pop culture icons', 'Which doll from Mattel made her debut in 1959?', 'Barbie'],
  ['Movie musicals', 'Which 1978 movie musical starred John Travolta and Olivia Newton-John?', 'Grease'],
  ["Streaming", "Which South Korean survival drama became Netflix's global breakout hit in 2021?", "Squid Game"],
  ['Animation history', 'Which Disney film featured the songs "Let It Go" and "Do You Want to Build a Snowman?"', 'Frozen'],
  ['Comic book films', 'Which actor played Tony Stark in the Marvel Cinematic Universe?', 'Robert Downey Jr.'],
  ['TV prestige', 'Which chemistry-teacher-turned-drug-kingpin anchored Breaking Bad?', 'Walter White'],
  ['Movie trivia', 'Which 1999 film claimed "I see dead people"?', 'The Sixth Sense'],
  ['Celebrity families', 'Which singer is the daughter of Billy Ray Cyrus?', 'Miley Cyrus'],
  ['Music awards', 'Which rapper interrupted Taylor Swift at the 2009 MTV Video Music Awards?', 'Kanye West'],
  ["Reality TV", "Which chef is famous for shouting \"It's raw!\" on television?", "Gordon Ramsay"],
  ['Talk shows', 'Which host gave away cars by shouting "You get a car!"?', 'Oprah Winfrey'],
  ["Pop fandom", "Which singer's fans are famously called the BeyHive?", "Beyonce"],
  ['Franchises', 'Which long-running action series stars Vin Diesel as Dominic Toretto?', 'Fast & Furious'],
  ['TV trivia', 'Which mockumentary workplace comedy is set at Dunder Mifflin Scranton?', 'The Office'],
  ['Music streaming', 'Which Puerto Rican star released the album Un Verano Sin Ti?', 'Bad Bunny'],
  ['Horror icons', 'Which masked slasher says almost nothing and stalks Haddonfield?', 'Michael Myers'],
  ['Awards', 'Which film won Best Picture at the Oscars after La La Land was announced by mistake?', 'Moonlight'],
  ['Sitcom lore', 'Which character on Friends was known for saying "How you doin\'?"', 'Joey Tribbiani'],
  ['Celebrity business', 'Which singer founded Fenty Beauty?', 'Rihanna'],
  ["Movie memes", "Which actor's intense table-pound in Whiplash became a favorite online reaction clip?", "J. K. Simmons"],
  ['Superhero TV', 'Which series follows the adopted Hargreeves siblings saving the world repeatedly?', 'The Umbrella Academy']
];

const holidaySeasonalSeeds: TriviaSeed[] = [
  ['Halloween history', 'People once carved Halloween lanterns from what vegetable before pumpkins became common in North America?', 'Turnips'],
  ['Winter traditions', 'The Christmas carol "Jingle Bells" was originally written for which holiday?', 'Thanksgiving'],
  ['New Year customs', 'Eating 12 grapes at midnight is a New Year tradition associated with which country?', 'Spain'],
  ['Halloween folklore', 'Samhain marked the end of harvest and the start of winter in which culture?', 'Gaelic'],
  ['Christmas history', 'The modern image of Santa Claus was heavily shaped by the poem beginning with what phrase?', 'Twas the night before Christmas'],
  ['Valentine lore', 'Conversation hearts were originally inspired by what earlier candy trend?', 'Medical lozenges'],
  ["April traditions", "April Fools' Day is strongly associated with fish-shaped pranks in which country?", "France"],
  ["Thanksgiving", "The first Macy's Thanksgiving Day Parade featured live animals borrowed from where?", "The Central Park Zoo"],
  ['Christmas decorations', 'Tinsel was once made from what metal?', 'Silver'],
  ['Lunar New Year', 'Red envelopes traditionally symbolize luck and the warding off of what?', 'Bad spirits'],
  ['Easter history', 'The Easter bunny tradition was brought to America by immigrants from where?', 'Germany'],
  ['Halloween oddities', 'People once believed that on Halloween, looking into a mirror could reveal what?', 'Your future spouse'],
  ['Holiday feasts', 'The Yule log began as an actual what?', 'Large ceremonial log burned in a hearth'],
  ["New Year superstitions", "In some places, people clean the house before New Year's Day to avoid sweeping out what?", "Good luck"],
  ['Christmas music', 'The best-selling holiday single of all time is commonly said to be which song?', 'White Christmas'],
  ['Valentine symbols', 'Cupid is the Roman version of which Greek god?', 'Eros'],
  ["Harvest festivals", "The jack-o'-lantern name comes from an Irish folktale about a man named what?", "Stingy Jack"],
  ['Winter drinks', 'Traditional wassail was originally a hot drink made with ale or cider and what fruit?', 'Roasted apples'],
  ['Ghost stories', 'Telling ghost stories at Christmas became especially popular in which century?', 'The Victorian era'],
  ["Seasonal fashion", "Ugly Christmas sweaters became mainstream partly because of which decade's ironic nostalgia?", "The 1980s"],
  ['Halloween treats', 'The phrase "trick or treat" became common in the United States around which decade?', 'The 1930s'],
  ['Carnival', 'Mardi Gras means "Fat Tuesday" in which language?', 'French'],
  ['Holiday flowers', 'Poinsettias are named after a U.S. diplomat to which country?', 'Mexico'],
  ['Seasonal folklore', 'Krampus is associated with punishing naughty children in Alpine regions during which season?', 'Christmas season'],
  ['Bonfire Night', 'Guy Fawkes Night is observed each year on what date?', 'November 5'],
  ['Holiday symbols', 'The menorah used during Hanukkah has how many branches?', 'Nine'],
  ['Spring rituals', 'Maypole dancing is traditionally linked to which month?', 'May'],
  ["New Year noise", "Noisemakers on New Year's Eve were historically meant to scare away what?", "Evil spirits"],
  ['Winter greenery', 'Mistletoe was sacred to which ancient priestly class?', 'Druids'],
  ["Holiday films", "The line \"Every time a bell rings, an angel gets his wings\" comes from which film?", "It's a Wonderful Life"],
  ['Halloween myths', 'Black cats became linked to Halloween partly because of associations with whom?', 'Witches'],
  ['Easter customs', 'The White House Easter Egg Roll takes place on what lawn?', 'The South Lawn'],
  ['Seasonal food', 'Hot cross buns are traditionally associated with which holiday?', 'Good Friday / Easter'],
  ['Christmas origins', 'The song "Silent Night" was first performed in which country?', 'Austria'],
  ["Thanksgiving broadcasts", "The first televised Macy's parade aired nationally on which network?", "CBS"],
  ['Lunar traditions', 'Mooncakes are associated with which festival?', 'The Mid-Autumn Festival'],
  ['Spooky season', 'The word "witch" comes from an Old English term most closely tied to what idea?', 'Bending or shaping'],
  ['Winter customs', 'Boxing Day is celebrated on the day after which holiday?', 'Christmas'],
  ['Festive plants', 'Holly became a winter decoration partly because its evergreen leaves symbolized what?', 'Endurance through winter'],
  ['Party traditions', 'A masquerade ball is most associated with wearing what?', 'Masks'],
  ['Holiday mascots', 'Rudolph first appeared as a character in a promotional booklet for which store?', 'Montgomery Ward'],
  ['New Year history', 'The dropping ball in Times Square was introduced after the city banned what older celebration practice?', 'Fireworks'],
  ['Halloween entertainment', 'Bobbing for apples likely comes from a Roman harvest tradition honoring which goddess?', 'Pomona'],
  ['Seasonal greetings', 'The phrase "Merry Christmas" became widely popularized in print by which author?', 'Charles Dickens'],
  ['Holiday sounds', 'A sleigh bell is technically a type of what instrument?', 'Jingle bell / small percussion bell'],
  ['Winter festivals', 'The Scandinavian celebration Lucia Day centers around a crown of what?', 'Candles'],
  ['Spooky folklore', 'People once believed that carrying a lantern made from a turnip would ward off what?', 'Restless spirits'],
  ["Spring pranks", "Some historians link April Fools' traditions to confusion around calendar reforms in which country?", "France"],
  ['Holiday baking', 'Gingerbread houses became especially popular after the publication of which fairy tale?', 'Hansel and Gretel'],
  ['Festive colors', 'Red and green Christmas color pairing became widespread partly because of what plant pairing?', 'Holly and mistletoe']
];

const nicheTriviaSeeds: TriviaSeed[] = [
  ['History', 'What tiny ingredient once helped preserve ancient Egyptian mummies and later flavored food?', 'Natron'],
  ['Internet culture', 'The term "rickroll" comes from bait-and-switch culture that evolved out of which earlier prank?', 'Duckrolling'],
  ['Board games', 'In chess notation, what does the abbreviation "en passant" literally mean in French?', 'In passing'],
  ["Music theory", "A tritone is often nicknamed what spooky interval?", "The devil's interval"],
  ['Printing', 'A widow in typography refers to what?', 'A short last line stranded at the top of a page or column'],
  ["Books", "The edge opposite a book's spine is called what?", "The fore-edge"],
  ['Gaming', 'The Konami Code begins with what two directional inputs?', 'Up, up'],
  ['Comics', 'What does DC originally stand for in DC Comics?', 'Detective Comics'],
  ['Mycology', 'The underground threadlike body of a fungus is called what?', 'Mycelium'],
  ['Maps', 'A map that preserves compass direction from a point is called an what projection?', 'Azimuthal'],
  ['Cooking', 'The browned bits stuck to a pan after searing are called what in French cooking?', 'Fond'],
  ['Knots', 'What knot is famous for making bunny-ear loops when tying shoes?', 'The bow knot'],
  ['Fashion', 'The small pocket inside many jeans was originally designed to hold what?', 'A pocket watch'],
  ['Typography', 'The little tail on a lowercase g or y is called what?', 'Descender'],
  ['Art history', 'A painting done on wet plaster is called a what?', 'Fresco'],
  ['Linguistics', 'A spoonerism swaps what between words?', 'Initial sounds'],
  ['Astronomy', 'The bright belt in the night sky made of many stars is our what galaxy?', 'Milky Way'],
  ['Calligraphy', 'Blackletter script is also sometimes known by what dramatic nickname?', 'Gothic script'],
  ['Architecture', 'The rounded triangular section over a doorway is called a what?', 'Pediment'],
  ['Food science', 'The cloudiness in anise spirits like ouzo after adding water is called the what effect?', 'Louche effect'],
  ['Bicycles', 'The fixed gear cog on a bike is attached to what part of the rear wheel?', 'The hub'],
  ['Oceanography', 'The deepest part of the ocean is in which trench?', 'The Mariana Trench'],
  ['Perfume', 'The base alcohol traditionally used in perfume is usually what kind of alcohol?', 'Ethanol'],
  ['Paper craft', 'The Japanese art of paper folding is called what?', 'Origami'],
  ['Museums', 'A label placed next to an exhibit object is often called a what?', 'Placard'],
  ['Tea culture', 'Matcha differs from most green tea because the leaves are what?', 'Ground into powder and consumed'],
  ['Radio', 'Morse code communicates through patterns of what two basic signal lengths?', 'Dots and dashes'],
  ['Nature', 'A murmuration refers to a flocking pattern most associated with which birds?', 'Starlings'],
  ['Textiles', 'Herringbone describes a repeating pattern that resembles the skeleton of what?', 'A herring fish'],
  ['Clocks', 'The swinging part of a traditional clock that regulates time is called a what?', 'Pendulum'],
  ['Theater', 'A monologue delivered while alone onstage and revealing private thoughts is called a what?', 'Soliloquy'],
  ['Maps', 'An inset map is a small secondary map used to show what?', 'Extra context or detail'],
  ['Cooking', 'A bain-marie is also commonly known as a what?', 'Water bath'],
  ['Seafaring', 'The left side of a ship is called what?', 'Port'],
  ['Photography', 'Bokeh refers to the quality of what part of an image?', 'The out-of-focus blur'],
  ['Poetry', 'A poem mourning the dead is called an what?', 'Elegy'],
  ["Magic", "The magician's term for a hidden method or gimmick is often what simple word?", "The secret"],
  ['Call centers', 'Phreaking originally referred to hacking what system?', 'Telephone networks'],
  ['Animation', 'The earliest pre-film spinning image toy is called a whatscope?', 'Phenakistiscope'],
  ['Weather', 'A sundog is a bright spot caused by sunlight interacting with what?', 'Ice crystals'],
  ['Music', 'The small bar supporting strings on a violin is called the what?', 'Bridge'],
  ['Stonework', 'A gargoyle specifically differs from a grotesque because it does what?', 'Acts as a waterspout'],
  ['Folklore', 'A cryptid is a creature whose existence is what?', 'Unproven'],
  ['Chess', 'The chess move that protects the king and develops a rook in one step is called what?', 'Castling'],
  ['Paper', 'Deckled edges on paper are intentionally what?', 'Rough or feathered'],
  ['Tools', 'The narrow strip of leather or cord that sharpens a straight razor is called a what?', 'Strop'],
  ['Science fiction', 'The word "robot" entered English from a Czech word meaning what?', 'Forced labor'],
  ['Fireworks', 'A fountain firework is designed to do what instead of exploding overhead?', 'Spray sparks from the ground'],
  ['Gardening', 'Espalier is the practice of training plants to grow what way?', 'Flat against a support'],
  ['Navigation', 'Dead reckoning estimates position using previous position, speed, and what else?', 'Direction']
];

const promptCatalog: Record<DeckId, PromptDefinition[]> = {
  truth_comes_out: truthComesOutSeeds.map((seed, index) => buildOpinionPrompt('truth_comes_out', index, seed)),
  is_that_a_fact: isThatAFactSeeds.map((seed, index) => buildTriviaPrompt('is_that_a_fact', index, seed)),
  movie_bluff: movieBluffSeeds.map((seed, index) => buildTriviaPrompt('movie_bluff', index, seed)),
  word_up: wordUpSeeds.map((seed, index) => buildTriviaPrompt('word_up', index, seed)),
  naked_truth: nakedTruthSeeds.map((seed, index) => buildOpinionPrompt('naked_truth', index, seed)),
  pop_culture: popCultureSeeds.map((seed, index) => buildTriviaPrompt('pop_culture', index, seed)),
  holiday_seasonal: holidaySeasonalSeeds.map((seed, index) => buildTriviaPrompt('holiday_seasonal', index, seed)),
  relationship_party: relationshipPartySeeds.map((seed, index) => buildOpinionPrompt('relationship_party', index, seed)),
  niche_trivia: nicheTriviaSeeds.map((seed, index) => buildTriviaPrompt('niche_trivia', index, seed))
};

export function getPromptsForDeck(deckId: DeckId) {
  return promptCatalog[deckId];
}

export function getAllPrompts() {
  return Object.values(promptCatalog).flat();
}
